git:
  depth: false
jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      language: elixir
      matrix:
        include:
          - elixir: 1.8.2
            otp_release: 20.2
          - elixir: 1.9.1
            otp_release: 22.1
      cache:
        directories:
          - _build
          - deps
      install:
        - bin/setup
      script:
        - MIX_ENV=test bin/test
    - stage: deploy
      if: branch = master
      script: skip
      deploy:
        provider: script
        script: bin/deploy
        on:
          all_branches: true
