git:
  depth: false
language: elixir
elixir:
  - 1.7.2
  - 1.9.1
otp_release:
  - 19.3
  - 22.0
matrix:
  exclude:
    - elixir: 1.7.2
      otp_release: 22.0
    - elixir: 1.9.1
      otp_release: 19.3
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
install:
  - bin/ci_setup
script:
  - bin/ci
after_script:
  - bin/coverage_ci
jobs:
  include:
    - if: tag IS blank
      stage: deploy
      script: skip
      elixir: 1.9.1
      otp_release: 22.0
      before_deploy:
        - bin/ci_setup
      deploy:
        provider: script
        script: bin/deploy
        skip_cleanup: true
        on:
          tags: true
